/* 
 * Yahoo Finance Quote API
 *
 * This is the API from yahoo finance to get quote for symbols.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kobeyoung81@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing QuoteResponseContentQuoteResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class QuoteResponseContentQuoteResponseTests
    {
        // TODO uncomment below to declare an instance variable for QuoteResponseContentQuoteResponse
        //private QuoteResponseContentQuoteResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of QuoteResponseContentQuoteResponse
            //instance = new QuoteResponseContentQuoteResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of QuoteResponseContentQuoteResponse
        /// </summary>
        [Test]
        public void QuoteResponseContentQuoteResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" QuoteResponseContentQuoteResponse
            //Assert.IsInstanceOfType<QuoteResponseContentQuoteResponse> (instance, "variable 'instance' is a QuoteResponseContentQuoteResponse");
        }


        /// <summary>
        /// Test the property 'Result'
        /// </summary>
        [Test]
        public void ResultTest()
        {
            // TODO unit test for the property 'Result'
        }

    }

}
