/* 
 * Yahoo Finance Quote API
 *
 * This is the API from yahoo finance to get quote for symbols.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kobeyoung81@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing QuoteResponseContent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class QuoteResponseContentTests
    {
        // TODO uncomment below to declare an instance variable for QuoteResponseContent
        //private QuoteResponseContent instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of QuoteResponseContent
            //instance = new QuoteResponseContent();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of QuoteResponseContent
        /// </summary>
        [Test]
        public void QuoteResponseContentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" QuoteResponseContent
            //Assert.IsInstanceOfType<QuoteResponseContent> (instance, "variable 'instance' is a QuoteResponseContent");
        }


        /// <summary>
        /// Test the property 'QuoteResponse'
        /// </summary>
        [Test]
        public void QuoteResponseTest()
        {
            // TODO unit test for the property 'QuoteResponse'
        }
        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Test]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }

    }

}
