/* 
 * Yahoo Finance Quote API
 *
 * This is the API from yahoo finance to get quote for symbols.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kobeyoung81@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp.Portable;
using YahooFinance.Quote.Client;
using YahooFinance.Quote.Model;

namespace YahooFinance.Quote.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface IDefaultApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// get quote for symbol
        /// </summary>
        /// <remarks>
        /// By passing in the appropriate options, you can search for available inventory in the system 
        /// </remarks>
        /// <exception cref="YahooFinance.Quote.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="symbols">pass an optional search string for looking up inventory</param>
        /// <returns>QuoteContent</returns>
        QuoteContent GetQuote (string symbols);

        /// <summary>
        /// get quote for symbol
        /// </summary>
        /// <remarks>
        /// By passing in the appropriate options, you can search for available inventory in the system 
        /// </remarks>
        /// <exception cref="YahooFinance.Quote.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="symbols">pass an optional search string for looking up inventory</param>
        /// <returns>ApiResponse of QuoteContent</returns>
        ApiResponse<QuoteContent> GetQuoteWithHttpInfo (string symbols);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// get quote for symbol
        /// </summary>
        /// <remarks>
        /// By passing in the appropriate options, you can search for available inventory in the system 
        /// </remarks>
        /// <exception cref="YahooFinance.Quote.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="symbols">pass an optional search string for looking up inventory</param>
        /// <returns>Task of QuoteContent</returns>
        System.Threading.Tasks.Task<QuoteContent> GetQuoteAsync (string symbols);

        /// <summary>
        /// get quote for symbol
        /// </summary>
        /// <remarks>
        /// By passing in the appropriate options, you can search for available inventory in the system 
        /// </remarks>
        /// <exception cref="YahooFinance.Quote.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="symbols">pass an optional search string for looking up inventory</param>
        /// <returns>Task of ApiResponse (QuoteContent)</returns>
        System.Threading.Tasks.Task<ApiResponse<QuoteContent>> GetQuoteAsyncWithHttpInfo (string symbols);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class DefaultApi : IDefaultApi
    {
        private YahooFinance.Quote.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DefaultApi(String basePath)
        {
            this.Configuration = new YahooFinance.Quote.Client.Configuration { BasePath = basePath };

            ExceptionFactory = YahooFinance.Quote.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultApi"/> class
        /// </summary>
        /// <returns></returns>
        public DefaultApi()
        {
            this.Configuration = YahooFinance.Quote.Client.Configuration.Default;

            ExceptionFactory = YahooFinance.Quote.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public DefaultApi(YahooFinance.Quote.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = YahooFinance.Quote.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = YahooFinance.Quote.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public YahooFinance.Quote.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public YahooFinance.Quote.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// get quote for symbol By passing in the appropriate options, you can search for available inventory in the system 
        /// </summary>
        /// <exception cref="YahooFinance.Quote.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="symbols">pass an optional search string for looking up inventory</param>
        /// <returns>QuoteContent</returns>
        public QuoteContent GetQuote (string symbols)
        {
             ApiResponse<QuoteContent> localVarResponse = GetQuoteWithHttpInfo(symbols);
             return localVarResponse.Data;
        }

        /// <summary>
        /// get quote for symbol By passing in the appropriate options, you can search for available inventory in the system 
        /// </summary>
        /// <exception cref="YahooFinance.Quote.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="symbols">pass an optional search string for looking up inventory</param>
        /// <returns>ApiResponse of QuoteContent</returns>
        public ApiResponse< QuoteContent > GetQuoteWithHttpInfo (string symbols)
        {
            // verify the required parameter 'symbols' is set
            if (symbols == null)
                throw new ApiException(400, "Missing required parameter 'symbols' when calling DefaultApi->GetQuote");

            var localVarPath = "./quote";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (symbols != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "symbols", symbols)); // query parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetQuote", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<QuoteContent>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (QuoteContent) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(QuoteContent)));
        }

        /// <summary>
        /// get quote for symbol By passing in the appropriate options, you can search for available inventory in the system 
        /// </summary>
        /// <exception cref="YahooFinance.Quote.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="symbols">pass an optional search string for looking up inventory</param>
        /// <returns>Task of QuoteContent</returns>
        public async System.Threading.Tasks.Task<QuoteContent> GetQuoteAsync (string symbols)
        {
             ApiResponse<QuoteContent> localVarResponse = await GetQuoteAsyncWithHttpInfo(symbols);
             return localVarResponse.Data;

        }

        /// <summary>
        /// get quote for symbol By passing in the appropriate options, you can search for available inventory in the system 
        /// </summary>
        /// <exception cref="YahooFinance.Quote.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="symbols">pass an optional search string for looking up inventory</param>
        /// <returns>Task of ApiResponse (QuoteContent)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<QuoteContent>> GetQuoteAsyncWithHttpInfo (string symbols)
        {
            // verify the required parameter 'symbols' is set
            if (symbols == null)
                throw new ApiException(400, "Missing required parameter 'symbols' when calling DefaultApi->GetQuote");

            var localVarPath = "./quote";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (symbols != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "symbols", symbols)); // query parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetQuote", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<QuoteContent>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (QuoteContent) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(QuoteContent)));
        }

    }
}
